INDIGO_WELCOME_MESSAGE: ""
INDIGO_PRIMARY_COLOR: "#397cb4" # hot blue

# Footer links are dictionaries with a "title" and "url"
# To remove all links, write:
# INDIGO_FOOTER_NAV_LINKS: []
# INDIGO_FOOTER_LEGAL_LINKS: []
INDIGO_FOOTER_NAV_LINKS:
  - title: ""
    url: ""
INDIGO_FOOTER_LEGAL_LINKS:
    - title: "© 2020 Digital Generation, by Raisense. All rights reserved"
      url: "/"
